cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:program_id>', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:program_id>', views.remove_from_cart, name='remove_from_cart'),
]

programs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.programs, name='programs'),
    path('<int:program_id>', views.program_details, name='program_details'),
    path('edit_program/<int:program_id>', views.edit_program, name='edit_program'),
    path('delete_program/<int:program_id>', views.delete_program, name='delete_program'),
    path('add_program/', views.add_program, name='add_program'),
]

sculpt_studio/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('programs/', include('programs.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('testimonials/', include('testimonials.urls')),
    path('partners/', include('partners.urls')),
    path('purchase/', include('purchase.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = 'home.views.page_not_found'
handler500 = 'home.views.server_error'

programs/models.py
from django.db import models

# Create your models here.

class Programs(models.Model):
    """
    model for different programs on sale
    """

    class Meta:
        verbose_name_plural = 'Programs'

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name 

testimonials/models.py
from django.db import models
from programs.models import Programs
from django.contrib.auth.models import User
from django.utils import timezone



class Testimonials(models.Model):

    class Meta():
        verbose_name_plural = 'Testimonials'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    program_id = models.ForeignKey(Programs, on_delete=models.CASCADE, null=True)
    review = models.TextField(max_length=2064)
    score = models.PositiveIntegerField(default=0, choices=([i,i] for i in range(11)))
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.user.username

programs/forms.py
from django import forms
from django.forms import ModelForm
from .models import Programs


class ProgramForm(forms.ModelForm):
    """
    return all fields from progrmas model
    """
    class Meta:
        model = Programs
        fields = '__all__'

programs/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Programs
from .forms import ProgramForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages



def programs(request):
    """
    render programs.html
    """
    programs = Programs.objects.all()

    context = {
        'programs': programs,
    }


    return render(request, 'programs/programs.html', context)


def program_details(request, program_id):
    """
    renders details about specific fitness program
    """
    programs = get_object_or_404(Programs, pk=program_id)

    context = {
        'programs': programs
    }

    return render(request, 'programs/program_details.html', context)


@login_required
def edit_program(request, program_id):
    """
    renders edit pagefor specific program
    """
    programs = get_object_or_404(Programs, pk=program_id)

    if not request.user.is_superuser:
        messages.error(request, f'You must be and administrative user to use this function')
        return redirect(reverse('home'))


    if request.method == 'POST':
        form = ProgramForm(request.POST, instance=programs)
        if form.is_valid:
            form.save()
            return redirect(reverse('program_details', args=[programs.id]))
    else:
        form = ProgramForm(instance=programs)

    context = {
        'programs': programs,
        'form': form
    }

    return render(request, 'programs/edit_program.html', context)


@login_required
def delete_program(request, program_id):
    """
    delete specific program
    """

    programs = get_object_or_404(Programs, pk=program_id)

    if not request.user.is_superuser:
        messages.error(request, f'You must be and administrative user to use this function')
        return redirect(reverse('home'))


    programs.delete()

    return redirect(reverse('programs'))



@login_required
def add_program(request):
    """
    allow admin users to add new programs program
    """

    if not request.user.is_superuser:
        messages.error(request, f'You must be and administrative user to use this function')
        return redirect(reverse('home'))


    if request.method == 'POST':
        form = ProgramForm(request.POST)
        if form.is_valid:
            program = form.save()
            return redirect(reverse('program_details', args=[program.id]))
    else:
        form = ProgramForm()

    context = {
        'form': form
    }

    return render(request, 'programs/add_programs.html', context)

programs/templates/programs/add_programs.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-8">
        <form action="{% url 'add_program' %}" method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <a href="{% url 'account' %}" class="btn btn-dark btn-primary">Back</a>
            <button type="submit" class="btn btn-primary">Confirm</button>
        </form>
    </div>
</div>

{% endblock %}

programs/templates/programs/edit_program.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-8">
        <form action="{% url 'edit_program' programs.id %}" method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <a href="{% url 'programs' %}" class="btn btn-dark btn-primary">Back</a>
            <button type="submit" class="btn btn-primary">Confirm</button>
        </form>
    </div>
</div>

{% endblock %}

programs/templates/programs/program_details.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-8 cards">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ programs.name }}</h5>
        <p class="card-text">Description: <br><br>  {{ programs.description }}</p>
        <p class="card-text">Length: {{ programs.type }}</p>
        <p class="card-text">Price: {{ programs.price }}€</p>
        {% if request.user.is_authenticated and request.user.is_superuser %}
        <a href="{% url 'edit_program' programs.id %}" class="btn btn-danger">Edit</a>
        <a href="{% url 'delete_program' programs.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'programs' %}" class="btn btn-dark btn-primary">Back</a>
        {% else %}
        <form action="{% url 'add_to_cart' programs.id %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'programs' %}" class="btn btn-dark btn-primary">Back</a>
        <input type="submit" name="add" value="Add to cart" class="btn btn-success btn-primary"></input>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-center">
{% for testimonial in programs.testimonials_set.all %}
    <div class="col-sm-4 cards">
        <div class="card">
          <div class="card-body">
            <p class="card-text"><i>"{{ testimonial.review }}"</i></p>
            <p class="card-text">Reviewed By: <strong>{{ testimonial.user.first_name}}</strong></p>
            <p class="card-text">I purchased "{{ testimonial.program_id}}"</p> 
            <p class="card-text">Rating: {{ testimonial.score }}</p>
            <p class="card-text">Review date: {{ testimonial.date }}</p> 
            {% if request.user.is_superuser %}
            <a class="btn btn-danger btn-primary" href="{% url 'delete_testimonials' testimonial.id %}">Delete</a>
            {% endif %}
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

programs/templates/programs/programs.html
{% extends 'base.html' %}

{% block content %}


<div class="row justify-content-center">
  {% for program in programs %}
  <div class="col-sm-4 cards">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ program.name }}</h5>
        <p class="card-text">Length: {{ program.type }}</p>
        <p class="card-text">Price: {{ program.price }}€</p>
        {% if request.user.is_authenticated and request.user.is_superuser %}
        <a href="{% url 'account' %}" class="btn btn-dark btn-primary">Back</a>
        <a href="{% url 'program_details' program.id %}" class="btn btn-dark btn-primary">Details</a>
        <a href="{% url 'edit_program' program.id %}" class="btn btn-danger">Edit</a>
        <a href="{% url 'delete_program' program.id %}" class="btn btn-danger">Delete</a>
        {% else %}
        <form action="{% url 'add_to_cart' program.id %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'program_details' program.id %}" class="btn btn-dark btn-primary">Details</a>
        <input type="submit" name="add" value="Add to cart" class="btn btn-success btn-primary"></input>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}